#!/usr/bin/env bash

ghome=google.com
gdns=8.8.8.8
gifc=$(ip route | awk '/default/ { print $5 }')
gway=$(ip route | awk '/default/ { print $3 }')

if ping -q -c 5 "$ghome" >/dev/null 2>&1; then
  tput sgr0
  notify-send "You are connected to internet via interface \"$gifc\""
  tput sgr0
  exit 0
else
  if ping -q -c 5 "$gdns" >/dev/null 2>&1; then
    tput sgr0
    notify-send "Your DNS server(s) does not seem to be responding,"
    "/etc/resolv.conf file might be of interest to you"
    tput sgr0
    exit 1
  else
    if ping -q -c 5 "$gway" >/dev/null 2>&1; then
      tput sgr0
      notify-send "Problem seems to be with the ISP. Contact the ISP"
      tput sgr0
      exit 1
    else
      tput sgr0
      notify-send "Can't connect to either your router or your modem,"
      "Make sure the PC's network is properly configured."
      "Also make sure the router or modem is switched on."
      "Do check that network cable is correctly attached."
      "In case of wireless router check the signal level"
      tput sgr0
      exit 1
    fi
  fi
fi
