#! /bin/sh

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width 4
bspc config window_gap 6

bspc config split_ratio 0.52
bspc config single_monocle false
bspc config focus_follows_pointer false
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc config presel_feedback_color "#282828"
bspc config active_border_color "#458588"
bspc config focused_border_color "#458588"
bspc config normal_border_color "#282828"

# bspc rule -a "*" split_dir=east
bspc rule -a \* rectangle 600x500+0+0 center=true
bspc rule -a qimgv state=floating
# bspc rule -a sxiv state=floating
bspc rule -a Xarchiver state=floating layer=normal
bspc rule -a Tilix state=floating layer=normal
bspc rule -a Galculator state=floating layer=normal rectangle=800x600+0+0
bspc rule -a mpv state=floating layer=normal
bspc rule -a Pavucontrol:pavucontrol state=floating
bspc rule -a Lxappearance state=floating layer=normal
bspc rule -a color-picker state=floating layer=normal
bspc rule -a gimp state=floating layer=normal
# bspc rule -a Gimp desktop='^9' follow=on
# bspc rule -a obs desktop='^10' follow=on
# bspc rule -a librewolf desktop='^2' follow=on

# start up stuff
xsetroot -cursor_name left_ptr &
# /usr/bin/lxpolkit &

# /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

dunst -config ~/.config/bspwm/dunst/dunstrc &
# picom --config ~/.config/bspwm/picom/picom.conf --animations -b &

xwallpaper --zoom ~/.dotfiles/pictures/mar.png &

## Polybar or tint
~/.config/bspwm/scripts/polybar-bspwm &

# terminal
# /usr/bin/alacritty &

## apps for systray if enabled
# volumeicon &
# nm-applet &
# (re)load sxhkd for keybinds
if hash sxhkd >/dev/null 2>&1; then
	pkill sxhkd
	sleep 0.5
	sxhkd -c "$HOME/.config/bspwm/sxhkd/sxhkdrc" &
fi
