#! /bin/sh

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width			2
bspc config window_gap				6

bspc config split_ratio				0.5
bspc config single_monocle			false
bspc config focus_follows_pointer	true
bspc config borderless_monocle		true
bspc config gapless_monocle			true

# bspc config focused_border_color	"#29d7e2"
# bspc config normal_border_color		"#3C3C3C"
bspc config presel_feedback_color "#282828"
bspc config active_border_color		"#458588"
bspc config focused_border_color "#458588"
bspc config normal_border_color "#282828"

# bspc rule -a "*" split_dir=east
bspc rule -a \* rectangle 600x400+0+0 center=true
bspc rule -a qimgv state=floating
# bspc rule -a sxiv state=floating
bspc rule -a Xarchiver state=floating layer=normal
bspc rule -a Tilix state=floating layer=normal
bspc rule -a Galculator state=floating layer=normal rectangle=800x600+0+0
bspc rule -a mpv state=floating layer=normal
bspc rule -a Pavucontrol:pavucontrol state=floating 
bspc rule -a Lxappearance state=floating layer=normal
bspc rule -a color-picker state=floating layer=normal
bspc rule -a gimp state=floating layer=normal 
# bspc rule -a Gimp desktop='^9' follow=on
# bspc rule -a obs desktop='^10' follow=on
# bspc rule -a discord desktop='^8' follow=on

# start up stuff
xsetroot -cursor_name left_ptr &
# /usr/bin/lxpolkit &
dunst -config ~/.config/bspwm/dunst/dunstrc &
# picom --config ~/.config/bspwm/picom/picom.conf --animations -b &
xwallpaper --zoom ~/.dotfiles/images/k9TDJg6.png &

## Polybar or tint
# ~/.config/bspwm/scripts/polybar-bspwm &

## apps for systray if enabled
# volumeicon &
# nm-applet &
# (re)load sxhkd for keybinds
if hash sxhkd >/dev/null 2>&1; then
	pkill sxhkd
	sleep 0.5
	sxhkd -c "$HOME/.config/bspwm/sxhkd/sxhkdrc" &
fi
