#! /bin/sh

# autostart
export DESKTOP_SESSION=bspwm

bspc monitor -d 1 2 3 4 5 6 7

bspc config border_width 2
bspc config window_gap 10

bspc config split_ratio 0.5
bspc config single_monocle false
bspc config focus_follows_pointer false
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc config presel_feedback_color "#1E1D2F"
bspc config active_border_color "#7AA2F7"
bspc config focused_border_color "#7AA2F7"
bspc config normal_border_color "#1E1D2F"

bspc rule -a "*" split_dir=east
bspc rule -a \* rectangle 600x500+0+0 center=true
bspc rule -a qimgv state=floating
bspc rule -a Xarchiver state=floating layer=normal
# bspc rule -a Galculator state=floating layer=normal
bspc rule -a mpv state=floating layer=normal
bspc rule -a Pavucontrol:pavucontrol state=floating
bspc rule -a Lxappearance state=floating layer=normal
bspc rule -a color-picker state=floating layer=normal
# bspc rule -a gimp state=floating layer=normal

# start up stuff
xsetroot -cursor_name left_ptr &

# /usr/bin/lxpolkit &
# /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &


dunst -config ~/.config/bspwm/dunst/dunstrc &

hsetroot -cover ~/.dotfiles/pictures/fabrizio-conti-c3wsMnxQZDw-unsplash.jpg &
# feh --bg-scale ~/.dotfiles/pictures/fabrizio-conti-c3wsMnxQZDw-unsplash.jpg &

~/.config/bspwm/scripts/polybar-bspwm &

# /usr/bin/alacritty &

## apps for systray if enabled
# volumeicon &
# nm-applet &

# gammastep &

# (re)load sxhkd for keybinds
if hash sxhkd >/dev/null 2>&1; then
	pkill sxhkd
	sleep 0.5
	sxhkd -c "$HOME/.config/bspwm/sxhkd/sxhkdrc" &
fi
