[font]
normal = { family = "JetBrainsMono Nerd Font Mono" , style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font Mono" , style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font Mono" , style = "Italic" }
size = 10.0
offset = { x = 0, y = 5 }
glyph_offset = { x = 0, y = 0 }
