require("options")
require("commands")
require("mappings")

require("colors.gruvbox")

require("plugins._treesitter")
require("plugins.blink")
require("plugins.fterm")
require("plugins.grugfar")
require("plugins.logsitter")
require("plugins.lsp")
require("plugins.mason")
require("plugins.mini")
require("plugins.oklchcolorpicker")
require("plugins.tsautotag")
require("plugins.visualmulti")
require("plugins.whichkey")
