require("options")
require("commands")
require("mappings")

require("colors.onedark")
require("plugins.lsp")
require("plugins.treesitter")

require("plugins.blink")
require("plugins.fterm")
require("plugins.grugfar")
require("plugins.logsitter")
require("plugins.mason")
require("plugins.minifiles")
require("plugins.minimove")
require("plugins.minipairs")
require("plugins.minipick")
require("plugins.minidiff")
require("plugins.oklchcolorpicker")
require("plugins.tsautotag")
require("plugins.visualmulti")
require("plugins.whichkey")

