#! /bin/sh
# ----------------------------------------------------------------------------
# Variables
# ----------------------------------------------------------------------------

# mod key (Alt=Mod1, Super=Mod4)
set $mod Mod4

# bindsym shortener
set $sup bindsym Mod4
# set $alt bindsym Mod1

# exec shortener
set $exe        exec --no-startup-id
set $exe_always exec_always --no-startup-id

# user local bin path (usually '~/bin' or '~/.local/bin')
set $bin_path ~/bin

# direction keys
set $ukey Up
set $dkey Down
set $lkey Left
set $rkey Right

# float enable
set $is_float floating enable

# default terminal
set $exe_term exec --no-startup-id sakura

# default theme for geany
set $exe_geany exec --no-startup-id geany

# colors
set $darker   #080910
set $dark     #181920
set $black    #2F343F
set $darkgray #3B4252
set $gray     #E7E8EB
set $white    #F5F6F7
set $red      #BF616A
set $orange   #DBAB6B
set $yellow   #EBCB8B
set $green    #A3BE8C
set $cyan     #88C0D0
set $blue     #91B1D1
set $darkblue #416181
set $purple   #B48EAD

bindsym XF86MonBrightnessUp exec --no-startup-id brightnessctl -c backlight set +5%  
bindsym XF86MonBrightnessDowm exec --no-startup-id brightnessctl -c backlight set 5%-  

bindsym XF86AudioRaiseVolume exec --no-startup-id pactl set-sink-volume @DEFAULT_SINK@ +5% 
bindsym XF86AudioLowerVolume exec --no-startup-id pactl set-sink-volume @DEFAULT_SINK@ -5% 

bindsym XF86AudioMute exec --no-startup-id pactl set-sink-mute @DEFAULT_SINK@ toggle 
bindsym XF86AudioMicMute exec --no-startup-id pactl set-source-mute @DEFAULT_SOURCE@ toggle 
# ----------------------------------------------------------------------------
# Workspaces
# ----------------------------------------------------------------------------

# labels

set $ws1  "1"
set $ws2  "2"
set $ws3  "3"
set $ws4  "4"
set $ws5  "5"
set $ws6  "6"
set $ws7  "7"
set $ws8  "8"
set $ws9  "9"


# switching
workspace_auto_back_and_forth yes

$sup+1 workspace $ws1
$sup+2 workspace $ws2
$sup+3 workspace $ws3
$sup+4 workspace $ws4
$sup+5 workspace $ws5
$sup+6 workspace $ws6
$sup+7 workspace $ws7
$sup+8 workspace $ws8
$sup+9 workspace $ws9

# moving to
$sup+Shift+1 move container to workspace $ws1;  workspace $ws1
$sup+Shift+2 move container to workspace $ws2;  workspace $ws2
$sup+Shift+3 move container to workspace $ws3;  workspace $ws3
$sup+Shift+4 move container to workspace $ws4;  workspace $ws4
$sup+Shift+5 move container to workspace $ws5;  workspace $ws5
$sup+Shift+6 move container to workspace $ws6;  workspace $ws6
$sup+Shift+7 move container to workspace $ws7;  workspace $ws7
$sup+Shift+8 move container to workspace $ws8;  workspace $ws8
$sup+Shift+9 move container to workspace $ws9;  workspace $ws9

# ----------------------------------------------------------------------------
# Windows
# ----------------------------------------------------------------------------

# Windowns defaults
for_window [class=".*"] border pixel 2
# default_border pixel 2
default_floating_border normal
hide_edge_borders smart
gaps inner 4
gaps outer 2

# focus defaults
focus_follows_mouse no
focus_wrapping no

# floating modes
floating_modifier Mod1

# Floating defaults
for_window [class="Lxappearance"]     $is_float
for_window [class="Nitrogen"]         $is_float
for_window [class="Gnome-calculator"] $is_float

# ----------------------------------------------------------------------------
# Key bindings
# ----------------------------------------------------------------------------

# workspace cycling
bindsym Ctrl+Mod1+Right      workspace next
bindsym Ctrl+Mod1+Left       workspace prev

# urgent workspace
$sup+u                       [urgent=latest] focus

# kill windows
$sup+q kill

# border type
$sup+b                       border toggle

# moving containers
$sup+Shift+$lkey             move left
$sup+Shift+$dkey             move down
$sup+Shift+$ukey             move up
$sup+Shift+$rkey             move right

# resizing containers
$sup+Mod1+$rkey           resize grow   width  5 px or 5 ppt
$sup+Mod1+$lkey           resize shrink width  5 px or 5 ppt
$sup+Mod1+$ukey           resize grow   height 5 px or 5 ppt
$sup+Mod1+$dkey           resize shrink height 5 px or 5 ppt

# floating windows
$sup+period                  floating toggle
$sup+comma                   focus mode_toggle

# session control
$sup+Shift+c                 reload
$sup+Shift+r                 restart
# $sup+Shift+Q                 $exe $bin_path/dmenu-i3-logout

# focus
$sup+$lkey                   focus left
$sup+$dkey                   focus down
$sup+$ukey                   focus up
$sup+$rkey                   focus right
$sup+Prior                   focus parent
$sup+Next                    focus child

# splitting

$sup+semicolon               split toggle

# layout switching

$sup+slash                   layout toggle splitv splith
$sup+Shift+question          layout toggle all
$sup+Shift+F11               fullscreen toggle

# screenshots
# bindsym Print                $exe xfce4-screenshooter -r -d 3
# bindsym Ctrl+Print           $exe xfce4-screenshooter -f -d 3
# bindsym Shift+Print          $exe xfce4-screenshooter -w -d 3

# ----------------------------------------------------------------------------
# Program launchers
# ----------------------------------------------------------------------------

# rofi show windows list
$sup+space                     $exe rofi -show drun -modi drun -line-padding 4 -hide-scrollbar -show-icons -theme ~/.config/i3/rofi/config.rasi

# Librewolf
$sup+w                       $exe librewolf

# Firefox
$sup+Shift+w                       $exe firefox

# PCManFM
$sup+f                 $exe pcmanfm

# Geany
$sup+e                       $exe_geany
$sup+Shift+e                 $exe_geany ~/.config/i3/config

# ----------------------------------------------------------------------------
# Terminals
# ----------------------------------------------------------------------------

$sup+Return                  $exe_term
$sup+t                       $exe_term

# ----------------------------------------------------------------------------
# Session startup
# ----------------------------------------------------------------------------

# $exe_always ~/.screenlayout/default.sh
$exe_always dunst -config ~/.config/bspwm/dunst/dunstrc &

$exe_always xset b off
# $exe_always nitrogen --restore
# $exe /usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1
# $exe nm-applet

