#!/bin/bash

# Close all dusnt alert
super + semicolon
  dunstctl close-all

# Launch Browser ()
super + w
  librewolf 

# Launch Browser ()
super + shift + w
  min

# Launch Terminal ()
super + Return
  alacritty	#sakura

# Launch Terminal ()
super + t
  alacritty #sakura 

# Launch Rofi Application Menu
super + space
  rofi -show drun -modi drun -line-padding 4 -hide-scrollbar -show-icons -theme ~/.config/bspwm/rofi/config.rasi

# Shutdown or Reboot
super + x
	~/.dotfiles/bspwm/.config/bspwm/scripts/power

# Show Keybinding Help Script
super + h
 ~/.dotfiles/bspwm/.config/bspwm/scripts/help

# Launch File Manager (Thunar)
super + f
	pcmanfm

# Launch Geany (Text Editor)
super + e
	geany

# Launch GIMP (Image Editor)
super + g
	gimp

# Set Window State: Tile Mode
super + shift + t
	bspc node -t tiled

# Set Window State: Floating Mode
super + shift + space
	bspc node -t floating

# Set Window State: Fullscreen Mode
super + shift + f
	bspc node -t fullscreen

# Reload sxhkd (Hotkey Daemon)
super + Escape
	pkill -USR1 -x sxhkd; notify-send 'sxhkd' 'Reloaded config'
	
# Reload bspwm (Window Manager)
super + shift + r
	bspc wm -r; notify-send 'bspwm' 'Restarted'

# Quit bspwm (Exit Window Manager)
super + shift + q
	bspc quit

# Close Focused Window
super + q
	bspc node -c

# Change Focus to Left Window
super + Left
	bspc node -f west

# Change Focus to Window Below
super + Down
	bspc node -f south

# Change Focus to Window Above
super + Up
	bspc node -f north

# Change Focus to Right Window
super + Right
	bspc node -f east

# Swap Focused Window with Left Window
super + shift + Left
	bspc node -s west

# Swap Focused Window with Window Below
super + shift + Down
	bspc node -s south

# Swap Focused Window with Window Above
super + shift + Up
	bspc node -s north

# Swap Focused Window with Right Window
super + shift + Right
	bspc node -s east

# Switch to Workspace 1-12
super + {1-9,0,F1,F2}
	bspc desktop --focus ^{1-9,10,11,12}

# Move Focused Window to Workspace 1-12
super + shift + {1-9,0,F1,F2}
	bspc node --to-desktop ^{1-9,10,11,12}

# Expand window width both sides
super + alt + Left
  bspc node -z right -40 0; bspc node -z left -40 0

# Shrink window width both sides 
super + alt + Right
  bspc node -z left 40 0; bspc node -z right 40 0

# Resize Window: Shrink Down
super + alt + Down
	bspc node -z top 0 40; bspc node -z bottom 40 0

# Resize Window: Shrink Up
super + alt + Up
	bspc node -z top 0 -40; bspc node -z up -40 0

# Mute Volume (Custom Script)
XF86AudioMute	
  amixer set Master toggle

# Increase Volume (Using amixer)
XF86AudioRaiseVolume
	amixer set Master 5%+

# Decrease Volume (Using amixer)
XF86AudioLowerVolume
	amixer set Master 5%-

# Increase Screen Brightness
XF86MonBrightnessUp
	brightnessctl -c backlight set +5%

# Decrease Screen Brightness
XF86MonBrightnessDown
	brightnessctl -c backlight set 5%-

# Take a Screenshot (Region Select)
super + shift + s
	flameshot gui --path ~/Screenshots/

# Enable Redshift (Night Light)
super + alt + r
	~/.dotfiles/bspwm/.config/bspwm/scripts/redshift-on

# Disable Redshift (Night Light)
super + alt + b
	~/.dotfiles/bspwm/.config/bspwm/scripts/redshift-off

# Take a Fullscreen Screenshot
super + s
	flameshot full --path ~/Screenshots/

# Resize All Windows Equally
super + equal
	bspc query -N -d | xargs -I % bspc node % -B
